#!/bin/bash
#PBS -q workq
#PBS -l nodes=1:ppn=20
#PBS -l walltime=3:00:00
#PBS -N pasta
#PBS -o raxml_pasta_CytB_Turtle.out
#PBS -j oe
#PBS -A loni_selu_sys
#PBS -m abe
#PBS -M zachary.nikolakis@selu.edu


module load java
module load python/3.5.2-anaconda-tensorflow
cd  /work/zach/SystematicsProject_Nikolakis/data/Turtle_output/

python ~/pasta/run_pasta.py -i CYTB_TUrtle.fasta  --tree-estimator=raxml -j Cytb_Turtle
